language: java
cache:
directories:
- $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- mvn clean package
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t pieterbogemans/destinationservice:latest .
- docker push pieterbogemans/destinationservice:latest 