language: java
cache:
directories:
- $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker images
- docker build -t pieterbogemans/destinationservice:latest .\target\dockerfile
- docker push pieterbogemans/destinationservice:latest